[package]
name = "sha"
version = "0.1.0"
edition = "2021"

[dependencies]
halo2_proofs = { path = "../halo2_proofs", features = ["dev-graph"] }
rand_core = { version = "0.6", default-features = false }
num-integer = "0.1.45"
num-bigint = "0.4.3"
num-traits = "0.2.15"
plotters = "0.3.5"
